services:

  msvc-eureka:
    build: ./service-eureka
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOST=msvc-eureka
    networks:
      - spring
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  msvc-gateway:
    build: ./service-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_HOST=msvc-eureka
    networks:
      - spring
    depends_on:
      msvc-eureka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  msvc-user: #Name of the msvc from application.yml
    build: ./service-user  # Route of Dockerfile
    ports:
      - "8081:8081"         # host:container
    environment:
      - USER_MSVC_DB_URL=${DOCKER_USER_MSVC_DB_URL}
      - USER_MSVC_DB_USER=${USER_MSVC_DB_USER}
      - USER_MSVC_DB_PASS=${USER_MSVC_DB_PASS}
      - EUREKA_HOST=msvc-eureka
    networks:
      - spring
    depends_on:
      msvc-eureka:
        condition: service_healthy
      msvc-user-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  msvc-user-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${USER_MSVC_DB_PASS}
      MYSQL_DATABASE: padel_user_service_db
    networks:
      - spring
    ports:
      - "3307:3306"
    volumes:
      - mysql-user-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  msvc-padel-court: #Name of the msvc from application.yml
    build: ./service-padel-court  # Route of Dockerfile
    ports:
      - "8083:8083"         # host:container
    environment:
      - DB_URL=jdbc:mysql://msvc-padel-court-db:3306/padel_padel_court_service_db?createDatabaseIfNotExist=true
      - DB_USER=root
      - DB_PASS=Zug55357
      - EUREKA_HOST=msvc-eureka
    networks:
      - spring
    depends_on:
      msvc-eureka:
        condition: service_healthy
      msvc-padel-court-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  msvc-padel-court-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zug55357
      MYSQL_DATABASE: padel_padel_court_service_db
    networks:
      - spring
    ports:
      - "3308:3306"
    volumes:
      - mysql-padel-court-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  msvc-auth:
    build: ./service-auth
    ports:
      - "8086:8086"
    environment:
      - AUTH_MSVC_DB_URL=${DOCKER_AUTH_MSVC_DB_URL}
      - AUTH_MSVC_DB_USER=${AUTH_MSVC_DB_USER}
      - AUTH_MSVC_DB_PASS=${AUTH_MSVC_DB_PASS}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - EUREKA_HOST=msvc-eureka
    networks:
      - spring
    depends_on:
      msvc-eureka:
        condition: service_healthy
      msvc-auth-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8086/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  msvc-auth-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${AUTH_MSVC_DB_PASS}
      MYSQL_DATABASE: padel_auth_service_db
    networks:
      - spring
    ports:
      - "3309:3306"
    volumes:
      - mysql-auth-db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10


volumes:
  mysql-padel-court-db-data:
  mysql-user-db-data:
  mysql-auth-db-data:

networks:
  spring:
    driver: bridge
