server:
  port: 8761

spring:
  application:
    name: msvc-eureka
  cloud:
    config:
      enabled: false

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    healthcheck:
      enabled: true
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
