spring:
  application:
    name: msvc-match-user
  cloud:
    config:
      enabled: false
  datasource:
    url: ${MATCH_USER_MSVC_DB_URL}
    username: ${MATCH_USER_MSVC_DB_USER}
    password: ${MATCH_USER_MSVC_DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8085

eureka:
  instance:
    hostname: ${MATCH_USER_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
