spring:
  application:
    name: msvc-auth
  datasource:
    url: jdbc:mysql://localhost:3306/padel_auth_service_db?createDatabaseIfNotExist=true
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

security:
  jwt:
    #${JWT_SECRET_KEY} Use environment variables to keep this key secret!
    secret-key: ${JWT_SECRET_KEY}
    expiration-time: 3600000  # 1 hour

server:
  port: 8086

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
